// <auto-generated />
using System;
using JoyModels.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoyModels.Models.src.Database.Migrations
{
    [DbContext(typeof(JoyModelsDbContext))]
    [Migration("20260124180750_AddReportTable")]
    partial class AddReportTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryName" }, "category_name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("d4363787-30b2-4cf9-b7ce-26dd2dce81ad"),
                            CategoryName = "Characters"
                        },
                        new
                        {
                            Uuid = new Guid("c72086e6-fe8c-480a-a918-f02cf632865e"),
                            CategoryName = "Humans"
                        },
                        new
                        {
                            Uuid = new Guid("8c76c6ad-d49d-4620-835b-333bf8996517"),
                            CategoryName = "Robots & Mechanics"
                        },
                        new
                        {
                            Uuid = new Guid("5457c9f7-a077-41c8-82cf-57cfd024b940"),
                            CategoryName = "Animals"
                        },
                        new
                        {
                            Uuid = new Guid("b4806536-be2d-4528-8548-1e7969efd599"),
                            CategoryName = "Plants & Vegetation"
                        },
                        new
                        {
                            Uuid = new Guid("e6a53e54-39af-4345-8cb1-3ba3650e85e8"),
                            CategoryName = "Rocks & Minerals"
                        },
                        new
                        {
                            Uuid = new Guid("5c76a1da-3881-4b95-8497-abea4c565a86"),
                            CategoryName = "Terrain & Landscapes"
                        },
                        new
                        {
                            Uuid = new Guid("228c1335-eef0-4c0c-b518-a36cfd237b00"),
                            CategoryName = "Buildings"
                        },
                        new
                        {
                            Uuid = new Guid("af71e3b2-7628-4492-a83d-36983526bfc3"),
                            CategoryName = "Interiors"
                        },
                        new
                        {
                            Uuid = new Guid("6f916b5b-2ca7-4174-a37f-04e4d203dfe8"),
                            CategoryName = "Props"
                        },
                        new
                        {
                            Uuid = new Guid("56aa06ec-c42b-4fb7-ac5e-322cf5dd5925"),
                            CategoryName = "Industrial & Factory"
                        },
                        new
                        {
                            Uuid = new Guid("0c09b371-eee6-4c1d-91e9-c0888f62545e"),
                            CategoryName = "Tools & Hardware"
                        },
                        new
                        {
                            Uuid = new Guid("6f8f81ea-232b-4fd7-8f90-fe5e61f2c87f"),
                            CategoryName = "Electronics & Gadgets"
                        },
                        new
                        {
                            Uuid = new Guid("81463c5f-aac3-4f99-bf8c-2b909b8b5c47"),
                            CategoryName = "Clothing & Accessories"
                        },
                        new
                        {
                            Uuid = new Guid("08edf884-994b-4f1c-9344-189a18904e9a"),
                            CategoryName = "Jewelry"
                        },
                        new
                        {
                            Uuid = new Guid("09798ef5-3756-4b3b-afbb-1d539efe0f35"),
                            CategoryName = "Sports & Fitness"
                        },
                        new
                        {
                            Uuid = new Guid("f4d84098-e750-4ca5-b71c-0c46b0b060f4"),
                            CategoryName = "Medical & Anatomy"
                        },
                        new
                        {
                            Uuid = new Guid("18ab38b1-7dee-4e4d-84ba-e3c6eb69d453"),
                            CategoryName = "Military"
                        },
                        new
                        {
                            Uuid = new Guid("b3d581f7-d746-4978-9c17-efe9002623d4"),
                            CategoryName = "Sci‑Fi"
                        },
                        new
                        {
                            Uuid = new Guid("3f838fcc-d267-4b46-999c-0f3e1bedc5d9"),
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            Uuid = new Guid("6362a527-9322-4820-91e7-36b1798913ea"),
                            CategoryName = "Horror"
                        },
                        new
                        {
                            Uuid = new Guid("056ae18c-6e0f-420b-9583-077cd7a483ff"),
                            CategoryName = "Musical Instruments"
                        },
                        new
                        {
                            Uuid = new Guid("b29ec84d-3951-4f1c-b881-7deba7c2f87d"),
                            CategoryName = "Office & Education"
                        },
                        new
                        {
                            Uuid = new Guid("e1d11f5a-f802-42ca-9dc3-981b8eafc4ff"),
                            CategoryName = "Boats & Ships"
                        },
                        new
                        {
                            Uuid = new Guid("98bfb9ab-cc57-4c13-9e45-9ef265e2092b"),
                            CategoryName = "Aircraft & Drones"
                        },
                        new
                        {
                            Uuid = new Guid("f34a3545-733c-42fa-8fad-82b3277d486f"),
                            CategoryName = "Spacecraft"
                        },
                        new
                        {
                            Uuid = new Guid("6aaeb356-5adc-4ceb-82b7-cf6f35e19df2"),
                            CategoryName = "Trains & Rail"
                        },
                        new
                        {
                            Uuid = new Guid("68737f63-995c-4ee0-8b01-4558e7fc2dd2"),
                            CategoryName = "Nature Elements"
                        },
                        new
                        {
                            Uuid = new Guid("eedc9940-378f-416b-9127-29f26985d6ed"),
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPost", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("CommunityPostCommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("community_post_comment_count");

                    b.Property<int>("CommunityPostDislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("community_post_dislikes");

                    b.Property<int>("CommunityPostLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("community_post_likes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("PostTypeUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("post_type_uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.Property<string>("YoutubeVideoLink")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("youtube_video_link");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PostTypeUuid" }, "post_type_uuid");

                    b.HasIndex(new[] { "UserUuid", "Title" }, "uq_user_title")
                        .IsUnique();

                    b.ToTable("community_posts", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostPicture", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CommunityPostUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("community_post_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("PictureLocation")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("picture_location");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommunityPostUuid", "PictureLocation" }, "uq_community_post_picture")
                        .IsUnique();

                    b.ToTable("community_post_pictures", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostQuestionSection", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CommunityPostUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("community_post_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<Guid?>("ParentMessageUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_message_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommunityPostUuid" }, "community_post_uuid");

                    b.HasIndex(new[] { "ParentMessageUuid" }, "parent_message_uuid");

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid");

                    b.ToTable("community_post_question_section", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostReviewType", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("ReviewName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("review_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReviewName" }, "review_name")
                        .IsUnique();

                    b.ToTable("community_post_review_types", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("86e4b752-2f94-4034-b22f-6dbf806b0fde"),
                            ReviewName = "Negative"
                        },
                        new
                        {
                            Uuid = new Guid("2e5c75b5-532f-4f5c-b86c-a9bdceb69e80"),
                            ReviewName = "Positive"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostType", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("CommunityPostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("community_post_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommunityPostName" }, "community_post_name")
                        .IsUnique();

                    b.ToTable("community_post_types", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("458c69e7-3d86-44c2-a9c1-336354d81643"),
                            CommunityPostName = "Guide"
                        },
                        new
                        {
                            Uuid = new Guid("662b1c39-8e30-4567-a874-d1188a88a8fb"),
                            CommunityPostName = "Post"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostUserReview", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CommunityPostUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("community_post_uuid");

                    b.Property<Guid>("ReviewTypeUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("review_type_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CommunityPostUuid" }, "community_post_uuid")
                        .HasDatabaseName("community_post_uuid1");

                    b.HasIndex(new[] { "ReviewTypeUuid" }, "review_type_uuid");

                    b.HasIndex(new[] { "UserUuid", "CommunityPostUuid" }, "uq_user_community_post")
                        .IsUnique();

                    b.ToTable("community_post_user_reviews", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Library", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("acquired_at");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<Guid>("OrderUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid");

                    b.HasIndex(new[] { "OrderUuid" }, "order_uuid");

                    b.HasIndex(new[] { "UserUuid", "ModelUuid" }, "uq_library_user_model")
                        .IsUnique();

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid1");

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Model", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LocationPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_path");

                    b.Property<Guid>("ModelAvailabilityUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_availability_uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LocationPath" }, "location_path")
                        .IsUnique();

                    b.HasIndex(new[] { "ModelAvailabilityUuid" }, "model_availability_uuid");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid2");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelAvailability", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("AvailabilityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("availability_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AvailabilityName" }, "availability_name")
                        .IsUnique();

                    b.ToTable("model_availability", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("65dcc8bf-4a87-4cc3-83e9-ee9dfdc937d9"),
                            AvailabilityName = "Hidden"
                        },
                        new
                        {
                            Uuid = new Guid("e1a7390c-ca8c-4914-83f2-15b0b3b96391"),
                            AvailabilityName = "Public"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelCategory", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("CategoryUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_uuid");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryUuid" }, "category_uuid");

                    b.HasIndex(new[] { "ModelUuid", "CategoryUuid" }, "uq_model_category")
                        .IsUnique();

                    b.ToTable("model_categories", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelFaqSection", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<Guid?>("ParentMessageUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_message_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid")
                        .HasDatabaseName("model_uuid1");

                    b.HasIndex(new[] { "ParentMessageUuid" }, "parent_message_uuid")
                        .HasDatabaseName("parent_message_uuid1");

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid3");

                    b.ToTable("model_faq_section", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelPicture", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<string>("PictureLocation")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("picture_location");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid", "PictureLocation" }, "uq_model_picture")
                        .IsUnique();

                    b.ToTable("model_pictures", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelReview", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<Guid>("ReviewTypeUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("review_type_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid")
                        .HasDatabaseName("model_uuid2");

                    b.HasIndex(new[] { "ReviewTypeUuid" }, "review_type_uuid")
                        .HasDatabaseName("review_type_uuid1");

                    b.HasIndex(new[] { "UserUuid", "ModelUuid" }, "uq_user_model_review")
                        .IsUnique();

                    b.ToTable("model_reviews", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelReviewType", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("ReviewName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("review_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReviewName" }, "review_name")
                        .IsUnique()
                        .HasDatabaseName("review_name1");

                    b.ToTable("model_review_types", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("410b9090-04da-4d0e-a641-719da1962d94"),
                            ReviewName = "Negative"
                        },
                        new
                        {
                            Uuid = new Guid("2e3b8189-4df1-42a0-8590-d3e6ec8b91d6"),
                            ReviewName = "Positive"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Notification", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ActorUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("actor_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("read_at");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<Guid>("RelatedEntityUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("related_entity_uuid");

                    b.Property<Guid>("TargetUserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_user_uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ActorUuid" }, "actor_uuid");

                    b.HasIndex(new[] { "CreatedAt" }, "created_at");

                    b.HasIndex(new[] { "IsRead" }, "is_read");

                    b.HasIndex(new[] { "TargetUserUuid" }, "target_user_uuid");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Order", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid")
                        .HasDatabaseName("model_uuid3");

                    b.HasIndex(new[] { "Status" }, "status");

                    b.HasIndex(new[] { "StripePaymentIntentId" }, "stripe_payment_intent_id");

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid4");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.PendingUser", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("char(12)")
                        .HasColumnName("otp_code")
                        .IsFixedLength();

                    b.Property<DateTime>("OtpCreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("otp_created_at");

                    b.Property<DateTime>("OtpExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("otp_expiration_date");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OtpCode" }, "otp_code")
                        .IsUnique();

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid5");

                    b.ToTable("pending_users", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Report", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reason");

                    b.Property<string>("ReportedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reported_entity_type");

                    b.Property<Guid>("ReportedEntityUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("reported_entity_uuid");

                    b.Property<Guid>("ReporterUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("reporter_uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("reviewed_by_uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ReportedEntityUuid" }, "reported_entity_uuid");

                    b.HasIndex(new[] { "ReporterUuid" }, "reporter_uuid");

                    b.HasIndex(new[] { "ReviewedByUuid" }, "reviewed_by_uuid");

                    b.HasIndex(new[] { "Status" }, "status")
                        .HasDatabaseName("status1");

                    b.HasIndex(new[] { "ReporterUuid", "ReportedEntityUuid" }, "uq_reporter_entity")
                        .IsUnique();

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid")
                        .HasDatabaseName("model_uuid4");

                    b.HasIndex(new[] { "UserUuid", "ModelUuid" }, "uq_user_model")
                        .IsUnique();

                    b.HasIndex(new[] { "UserUuid" }, "user_uuid")
                        .HasDatabaseName("user_uuid6");

                    b.ToTable("shopping_cart", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nick_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<int>("UserFollowerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("user_follower_count");

                    b.Property<int>("UserFollowingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("user_following_count");

                    b.Property<int>("UserLikedModelsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("user_liked_models_count");

                    b.Property<int>("UserModelsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("user_models_count");

                    b.Property<string>("UserPictureLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_picture_location");

                    b.Property<Guid>("UserRoleUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_role_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "NickName" }, "nick_name")
                        .IsUnique();

                    b.HasIndex(new[] { "UserRoleUuid" }, "user_role_uuid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserFollower", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("followed_at");

                    b.Property<Guid>("UserOriginUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_origin_uuid");

                    b.Property<Guid>("UserTargetUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_target_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserOriginUuid", "UserTargetUuid" }, "uq_unique_follow")
                        .IsUnique();

                    b.HasIndex(new[] { "UserTargetUuid" }, "user_target_uuid");

                    b.ToTable("user_followers", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserModelLike", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<Guid>("ModelUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_uuid");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelUuid" }, "model_uuid")
                        .HasDatabaseName("model_uuid5");

                    b.HasIndex(new[] { "UserUuid", "ModelUuid" }, "uq_user_model_like")
                        .IsUnique();

                    b.ToTable("user_model_likes", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "role_name")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("2107d612-ac38-4390-aeb6-276cf55b42bb"),
                            RoleName = "Unverified"
                        },
                        new
                        {
                            Uuid = new Guid("efd09239-1461-4740-86ae-94ed49137a36"),
                            RoleName = "User"
                        },
                        new
                        {
                            Uuid = new Guid("90051a72-89ea-48ca-8543-43f5843148c8"),
                            RoleName = "Helper"
                        },
                        new
                        {
                            Uuid = new Guid("44b4be39-2884-462a-98c0-cb3b5eb9c3dd"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Uuid = new Guid("c5c8ab92-5933-4122-a804-6533516aeb5d"),
                            RoleName = "Root"
                        });
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("TokenExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("token_expiration_date");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_uuid");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserUuid", "RefreshToken" }, "uq_user_refresh_token")
                        .IsUnique();

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPost", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPostType", "PostTypeUu")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("PostTypeUuid")
                        .IsRequired()
                        .HasConstraintName("community_posts_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_posts_ibfk_1");

                    b.Navigation("PostTypeUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostPicture", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPost", "CommunityPostUu")
                        .WithMany("CommunityPostPictures")
                        .HasForeignKey("CommunityPostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_post_pictures_ibfk_1");

                    b.Navigation("CommunityPostUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostQuestionSection", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPost", "CommunityPostUu")
                        .WithMany("CommunityPostQuestionSections")
                        .HasForeignKey("CommunityPostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_post_question_section_ibfk_3");

                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPostQuestionSection", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("community_post_question_section_ibfk_parent");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("CommunityPostQuestionSectionUserUus")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_post_question_section_ibfk_1");

                    b.Navigation("CommunityPostUu");

                    b.Navigation("ParentMessage");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostUserReview", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPost", "CommunityPostUu")
                        .WithMany("CommunityPostUserReviews")
                        .HasForeignKey("CommunityPostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_post_user_reviews_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.CommunityPostReviewType", "ReviewTypeUu")
                        .WithMany("CommunityPostUserReviews")
                        .HasForeignKey("ReviewTypeUuid")
                        .IsRequired()
                        .HasConstraintName("community_post_user_reviews_ibfk_3");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("CommunityPostUserReviews")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("community_post_user_reviews_ibfk_1");

                    b.Navigation("CommunityPostUu");

                    b.Navigation("ReviewTypeUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Library", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "Model")
                        .WithMany("Libraries")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("libraries_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("libraries_ibfk_3");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "User")
                        .WithMany("Libraries")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("libraries_ibfk_1");

                    b.Navigation("Model");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Model", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.ModelAvailability", "ModelAvailabilityUu")
                        .WithMany("Models")
                        .HasForeignKey("ModelAvailabilityUuid")
                        .IsRequired()
                        .HasConstraintName("models_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("Models")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("models_ibfk_1");

                    b.Navigation("ModelAvailabilityUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelCategory", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Category", "CategoryUu")
                        .WithMany("ModelCategories")
                        .HasForeignKey("CategoryUuid")
                        .IsRequired()
                        .HasConstraintName("model_categories_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("ModelCategories")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_categories_ibfk_1");

                    b.Navigation("CategoryUu");

                    b.Navigation("ModelUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelFaqSection", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("ModelFaqSections")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_faq_section_ibfk_3");

                    b.HasOne("JoyModels.Models.Database.Entities.ModelFaqSection", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("model_faq_section_ibfk_parent");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("ModelFaqSectionUserUus")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_faq_section_ibfk_1");

                    b.Navigation("ModelUu");

                    b.Navigation("ParentMessage");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelPicture", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("ModelPictures")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_pictures_ibfk_1");

                    b.Navigation("ModelUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelReview", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("ModelReviews")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_reviews_ibfk_1");

                    b.HasOne("JoyModels.Models.Database.Entities.ModelReviewType", "ReviewTypeUu")
                        .WithMany("ModelReviews")
                        .HasForeignKey("ReviewTypeUuid")
                        .IsRequired()
                        .HasConstraintName("model_reviews_ibfk_3");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("ModelReviews")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("model_reviews_ibfk_2");

                    b.Navigation("ModelUu");

                    b.Navigation("ReviewTypeUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Notification", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.User", "Actor")
                        .WithMany("NotificationsAsActor")
                        .HasForeignKey("ActorUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_ibfk_1");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "TargetUser")
                        .WithMany("NotificationsAsTarget")
                        .HasForeignKey("TargetUserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_ibfk_2");

                    b.Navigation("Actor");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Order", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "Model")
                        .WithMany("Orders")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_1");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.PendingUser", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("PendingUsers")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pending_users_ibfk_1");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Report", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.User", "Reporter")
                        .WithMany("ReportsAsReporter")
                        .HasForeignKey("ReporterUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reports_ibfk_1");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "ReviewedBy")
                        .WithMany("ReportsAsReviewer")
                        .HasForeignKey("ReviewedByUuid")
                        .HasConstraintName("reports_ibfk_2");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ShoppingCart", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_cart_items_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_cart_items_ibfk_1");

                    b.Navigation("ModelUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.User", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.UserRole", "UserRoleUu")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleUuid")
                        .IsRequired()
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("UserRoleUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserFollower", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserOriginUu")
                        .WithMany("UserFollowerUserOriginUus")
                        .HasForeignKey("UserOriginUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_followers_ibfk_1");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserTargetUu")
                        .WithMany("UserFollowerUserTargetUus")
                        .HasForeignKey("UserTargetUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_followers_ibfk_2");

                    b.Navigation("UserOriginUu");

                    b.Navigation("UserTargetUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserModelLike", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.Model", "ModelUu")
                        .WithMany("UserModelLikes")
                        .HasForeignKey("ModelUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_model_likes_ibfk_2");

                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("UserModelLikes")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_model_likes_ibfk_1");

                    b.Navigation("ModelUu");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserToken", b =>
                {
                    b.HasOne("JoyModels.Models.Database.Entities.User", "UserUu")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_tokens_ibfk_1");

                    b.Navigation("UserUu");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Category", b =>
                {
                    b.Navigation("ModelCategories");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPost", b =>
                {
                    b.Navigation("CommunityPostPictures");

                    b.Navigation("CommunityPostQuestionSections");

                    b.Navigation("CommunityPostUserReviews");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostQuestionSection", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostReviewType", b =>
                {
                    b.Navigation("CommunityPostUserReviews");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.CommunityPostType", b =>
                {
                    b.Navigation("CommunityPosts");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.Model", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("ModelCategories");

                    b.Navigation("ModelFaqSections");

                    b.Navigation("ModelPictures");

                    b.Navigation("ModelReviews");

                    b.Navigation("Orders");

                    b.Navigation("ShoppingCartItems");

                    b.Navigation("UserModelLikes");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelAvailability", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelFaqSection", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.ModelReviewType", b =>
                {
                    b.Navigation("ModelReviews");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.User", b =>
                {
                    b.Navigation("CommunityPostQuestionSectionUserUus");

                    b.Navigation("CommunityPostUserReviews");

                    b.Navigation("CommunityPosts");

                    b.Navigation("Libraries");

                    b.Navigation("ModelFaqSectionUserUus");

                    b.Navigation("ModelReviews");

                    b.Navigation("Models");

                    b.Navigation("NotificationsAsActor");

                    b.Navigation("NotificationsAsTarget");

                    b.Navigation("Orders");

                    b.Navigation("PendingUsers");

                    b.Navigation("ReportsAsReporter");

                    b.Navigation("ReportsAsReviewer");

                    b.Navigation("ShoppingCartItems");

                    b.Navigation("UserFollowerUserOriginUus");

                    b.Navigation("UserFollowerUserTargetUus");

                    b.Navigation("UserModelLikes");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("JoyModels.Models.Database.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
